services:
  mongo:
    image: mongo
    container_name: mongo_c
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - 3001:3001
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/db_node

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/db_node

volumes:
  mongo-data:
